// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 romcsibacsi
// This file is part of citadel (public open-core). See LICENSE.
// A commercial license without AGPL obligations is available — see COMMERCIAL-LICENSE.md (dual-license).
import type { DatabaseSync } from 'node:sqlite';
import { type Clock, systemClock, isoNow } from '../core/clock.js';
import type { MemoryStore } from './store.js';

/**
 * Daily logs + daily digest (SPEC §8/§9). The digest is plain deterministic
 * text assembly over daily_logs — it returns DATA for the learning loop, not
 * localized operator prose (operator-facing rendering localizes separately).
 */

const DAY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

export interface DailyDigest {
  summary: string;
  hadActivity: boolean;
}

/** Append one activity line for (agent, day). Returns the new row id. */
export function appendDailyLog(
  db: DatabaseSync,
  agentId: string,
  day: string,
  line: string,
  clock: Clock = systemClock,
): number {
  if (!DAY_PATTERN.test(day)) {
    throw new Error(`invalid day '${day}' — expected YYYY-MM-DD`);
  }
  const result = db
    .prepare('INSERT INTO daily_logs (agent_id, day, line, created_at) VALUES (?, ?, ?, ?)')
    .run(agentId, day, line, isoNow(clock));
  return Number(result.lastInsertRowid);
}

/**
 * Assemble the digest for one day from all agents' daily_logs lines, grouped
 * by agent in insertion order. hadActivity=false yields a fixed no-activity
 * summary so consumers (nightly consolidation) can branch on quiet days.
 */
export function buildDailyDigest(db: DatabaseSync, day: string): DailyDigest {
  const rows = db
    .prepare('SELECT agent_id, line FROM daily_logs WHERE day = ? ORDER BY agent_id, id')
    .all(day) as unknown as Array<{ agent_id: string; line: string }>;
  if (rows.length === 0) {
    return { summary: `Daily digest ${day}: no recorded activity.`, hadActivity: false };
  }
  const lines = rows.map((r) => `[${r.agent_id}] ${r.line}`);
  return {
    summary: `Daily digest ${day} (${rows.length} entries):\n${lines.join('\n')}`,
    hadActivity: true,
  };
}

/**
 * Persist a digest as an episodic memory of the day (SPEC §8). Category 'hot'
 * by design: it is recent activity and migrates to 'cold' through aging.
 */
export function writeDigestMemory(store: MemoryStore, agentId: string, day: string, summary: string): number {
  return store.save({
    agentId,
    category: 'hot',
    sector: 'episodic',
    content: summary,
    keywords: `daily digest ${day}`,
    autoGenerated: true,
  });
}
