// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 romcsibacsi
// This file is part of citadel (public open-core). See LICENSE.
// A commercial license without AGPL obligations is available — see COMMERCIAL-LICENSE.md (dual-license).
import type { DatabaseSync, StatementSync } from 'node:sqlite';
import { type Clock, systemClock, isoNow } from '../core/clock.js';
import { createLogger } from '../core/log.js';
import { sanitizeFtsQuery, tokenizeQuery } from './ftsQuery.js';
import { type EmbeddingProvider, embeddingToBlob, blobToEmbedding, cosineSimilarity } from './embedding.js';

const log = createLogger('memory-store');

/**
 * Memory tiers + recall (SPEC §8). Hard invariants:
 *  - 'shared' is the ONLY cross-agent visibility; recall always unions it.
 *  - Memories are NEVER deleted: decay lowers salience, aging moves hot→cold,
 *    archive stamps archived_at. There is no DELETE statement in this module.
 *  - Embeddings are async fire-and-forget and never block or fail a save.
 */

export type MemoryCategory = 'hot' | 'warm' | 'cold' | 'shared';
export type MemorySector = 'semantic' | 'episodic';

export interface MemoryRow {
  id: number;
  agentId: string;
  category: MemoryCategory;
  sector: MemorySector;
  content: string;
  keywords: string;
  salience: number;
  autoGenerated: boolean;
  createdAt: string;
  accessedAt: string | null;
  archivedAt: string | null;
}

export interface SaveMemoryInput {
  agentId: string;
  category: MemoryCategory;
  sector: MemorySector;
  content: string;
  keywords?: string;
  autoGenerated?: boolean;
}

export interface SearchOptions {
  limit?: number;
  /**
   * 'hybrid' fuses keyword + vector ranking; 'fts' is keyword-only. Honored only
   * when an embedding provider is configured — otherwise BOTH fall back to FTS
   * (there is nothing to vector-rerank). The UI is told via embeddingEnabled()
   * so it can hide the Hybrid option rather than silently pretending.
   */
  mode?: 'hybrid' | 'fts';
}

export interface ListOptions {
  category?: MemoryCategory;
  limit?: number;
  includeArchived?: boolean;
}

export interface UpdateMemoryPatch {
  content?: string;
  keywords?: string;
  category?: MemoryCategory;
}

export interface MemoryStats {
  total: number;
  byCategory: Record<MemoryCategory, number>;
  bySector: Record<MemorySector, number>;
  avgSalience: number;
  archived: number;
}

const SALIENCE_BOOST = 0.1;
const SALIENCE_CAP = 5.0; // spec §9: salience starts ~1.0, capped at ~5.0
const DEFAULT_DECAY_FACTOR = 0.98;
const DEFAULT_DECAY_FLOOR = 0.05;
const DEFAULT_SEARCH_LIMIT = 10;
const DEFAULT_LIST_LIMIT = 50;
const DAY_MS = 86_400_000;
// Hybrid fusion (FIX-memory-vectorization): widen the FTS candidate pool, cap the
// vector scan, and fuse normalized FTS rank with cosine. A vector-only row joins
// the result only above VEC_FLOOR so a query with no real neighbours doesn't pull
// in noise. FTS and vector contribute equally to the fused score.
const HYBRID_FTS_POOL = 3; // fetch limit*this FTS candidates before re-ranking
const HYBRID_VEC_CAP = 1000; // most-recent embedded rows in scope to score by cosine
const HYBRID_VEC_FLOOR = 0.5; // min cosine for a vector-ONLY (no FTS match) row to qualify
const HYBRID_FTS_WEIGHT = 0.5;
const HYBRID_VEC_WEIGHT = 0.5;

const ROW_COLUMNS =
  'id, agent_id, category, sector, content, keywords, salience, auto_generated, created_at, accessed_at, archived_at';

interface DbMemoryRow {
  id: number;
  agent_id: string;
  category: string;
  sector: string;
  content: string;
  keywords: string;
  salience: number;
  auto_generated: number;
  created_at: string;
  accessed_at: string | null;
  archived_at: string | null;
}

function mapRow(r: DbMemoryRow): MemoryRow {
  return {
    id: r.id,
    agentId: r.agent_id,
    category: r.category as MemoryCategory,
    sector: r.sector as MemorySector,
    content: r.content,
    keywords: r.keywords,
    salience: r.salience,
    autoGenerated: r.auto_generated === 1,
    createdAt: r.created_at,
    accessedAt: r.accessed_at,
    archivedAt: r.archived_at,
  };
}

export class MemoryStore {
  private readonly insertStmt: StatementSync;
  private readonly ftsStmt: StatementSync;
  private readonly boostStmt: StatementSync;
  private readonly archiveStmt: StatementSync;
  private readonly decayStmt: StatementSync;
  private readonly ageStmt: StatementSync;
  private readonly embedUpdateStmt: StatementSync;

  constructor(
    private readonly db: DatabaseSync,
    private readonly clock: Clock = systemClock,
    private readonly embedding?: EmbeddingProvider,
    /**
     * Agents that handle isolated sensitive data (#115/#117 customer-service end-customer
     * PII; #124d bookkeeper company financial data). They are STRUCTURALLY refused a write
     * to EVERY memory tier — the data lives only in their scoped store (cs_* / bk_*) + the
     * vault, never in memory. Empty by default, so the own fleet is unaffected.
     */
    private readonly memoryIsolatedAgents: ReadonlySet<string> = new Set(),
  ) {
    this.insertStmt = db.prepare(
      `INSERT INTO memories (agent_id, category, sector, content, keywords, salience, auto_generated, created_at)
       VALUES (?, ?, ?, ?, ?, 1.0, ?, ?)`,
    );
    // Recall scope (SPEC §8): own rows UNION the shared tier, never archived.
    this.ftsStmt = db.prepare(
      `SELECT ${columnsOf('m')} FROM memories m
       JOIN (SELECT rowid AS fid, rank AS score FROM memories_fts WHERE memories_fts MATCH ?) f
         ON f.fid = m.id
       WHERE (m.agent_id = ? OR m.category = 'shared') AND m.archived_at IS NULL
       ORDER BY f.score
       LIMIT ?`,
    );
    this.boostStmt = db.prepare(
      'UPDATE memories SET salience = MIN(?, salience + ?), accessed_at = ? WHERE id = ?',
    );
    this.archiveStmt = db.prepare('UPDATE memories SET archived_at = ? WHERE id = ? AND archived_at IS NULL');
    this.decayStmt = db.prepare(
      'UPDATE memories SET salience = MAX(?, salience * ?) WHERE archived_at IS NULL AND salience > ?',
    );
    this.ageStmt = db.prepare(
      `UPDATE memories SET category = 'cold'
       WHERE category = 'hot' AND archived_at IS NULL AND COALESCE(accessed_at, created_at) < ?`,
    );
    this.embedUpdateStmt = db.prepare('UPDATE memories SET embedding = ? WHERE id = ?');
  }

  /**
   * Persist a memory (salience starts at 1.0). Returns the new row id
   * synchronously; if an embedding provider is configured, vectorization is
   * scheduled fire-and-forget and can neither delay nor fail the save.
   */
  save(input: SaveMemoryInput): number {
    // #115/#117/#124d isolation (L1, structural; gate R5b/R5c): a memory-isolated agent
    // (customer-service / bookkeeper) may NEVER write to ANY memory tier. The shared tier
    // leaks to every agent's recall, but even an OWN tier (hot/warm/cold) leaks: recall
    // scope is (agent_id = ? OR shared), so the agent re-surfaces its own past rows — for
    // CS that crosses end-customers, for the bookkeeper it persists company financial data.
    // The agent's "memory" is its scoped store (cs_* / bk_*) + vault; generic process
    // learning lives in skills, not memory. CODE block, not a persona instruction.
    if (this.memoryIsolatedAgents.has(input.agentId)) {
      throw new Error(`memory: data-isolated agent '${input.agentId}' may not write to any memory tier (use its scoped store: cs_* / bk_*)`);
    }
    const result = this.insertStmt.run(
      input.agentId,
      input.category,
      input.sector,
      input.content,
      input.keywords ?? '',
      input.autoGenerated ? 1 : 0,
      isoNow(this.clock),
    );
    const id = Number(result.lastInsertRowid);
    this.scheduleEmbedding(id, input.content);
    return id;
  }

  /**
   * Recall: FTS over memories_fts with the sanitized query, scoped to the
   * agent's own rows UNION the shared tier, excluding archived. On FTS parse
   * error (defense in depth — sanitized queries should never fail) or when no
   * usable FTS token survives, falls back to LIKE '%token%' matching.
   * Returned rows get a salience boost (+0.1, capped at 2.0) and a fresh
   * accessed_at stamp; the returned objects reflect the post-boost state.
   */
  search(agentId: string, query: string, opts: SearchOptions = {}): MemoryRow[] {
    const limit = opts.limit ?? DEFAULT_SEARCH_LIMIT;
    const rows = this.ftsCandidates(agentId, query, limit);
    this.applyBoost(rows);
    return rows;
  }

  /**
   * Hybrid recall (FIX-memory-vectorization): fuse keyword (FTS) rank with vector
   * cosine similarity. Honored only when an embedding provider is configured and
   * `mode !== 'fts'`; otherwise (or on ANY embedding failure) it degrades to the
   * sync FTS `search()` — so a missing/unreachable ollama never breaks recall. It
   * surfaces semantically-related rows pure FTS would miss, and re-ranks the union
   * of the FTS pool + the nearest embedded neighbours. Async because embedding the
   * QUERY is async; callers that don't need vectors keep using sync `search()`.
   */
  async searchHybrid(agentId: string, query: string, opts: SearchOptions = {}): Promise<MemoryRow[]> {
    const provider = this.embedding;
    const limit = opts.limit ?? DEFAULT_SEARCH_LIMIT;
    if (provider === undefined || opts.mode === 'fts') return this.search(agentId, query, opts);

    let queryVec: Float32Array;
    try {
      queryVec = await provider.embed(query);
    } catch (err) {
      log.warn('query embed failed, falling back to FTS', { error: String(err) });
      return this.search(agentId, query, opts);
    }

    const scored = new Map<number, { row: MemoryRow; score: number }>();
    // FTS pool (widened), scored by descending rank position (1 → ~0).
    const ftsRows = this.ftsCandidates(agentId, query, limit * HYBRID_FTS_POOL);
    ftsRows.forEach((row, i) => {
      const ftsScore = ftsRows.length > 1 ? 1 - i / ftsRows.length : 1;
      scored.set(row.id, { row, score: HYBRID_FTS_WEIGHT * ftsScore });
    });
    // Vector neighbours: fuse cosine into FTS hits; admit a vector-ONLY row only
    // when it clears the floor (so an unrelated query can't drag in noise).
    for (const { row, vec } of this.embeddedRowsInScope(agentId, HYBRID_VEC_CAP)) {
      const cos = Math.max(0, cosineSimilarity(queryVec, vec));
      const prev = scored.get(row.id);
      if (prev !== undefined) prev.score += HYBRID_VEC_WEIGHT * cos;
      else if (cos >= HYBRID_VEC_FLOOR) scored.set(row.id, { row, score: HYBRID_VEC_WEIGHT * cos });
    }
    if (scored.size === 0) return this.search(agentId, query, opts);

    const top = [...scored.values()]
      .sort((a, b) => b.score - a.score)
      .slice(0, limit)
      .map((s) => s.row);
    this.applyBoost(top);
    return top;
  }

  /**
   * One-time/idempotent backfill (FIX-memory-vectorization): embed non-archived
   * rows that lack a vector, sequentially (throttled — one request at a time) so
   * it never hammers ollama. Bounded by `cap`; re-running continues where it left
   * off (only `embedding IS NULL` rows are touched). Non-fatal per row. No-op
   * without a provider. Call fire-and-forget at boot.
   */
  async backfillEmbeddings(opts: { cap?: number } = {}): Promise<number> {
    const provider = this.embedding;
    if (provider === undefined) return 0;
    const cap = opts.cap ?? HYBRID_VEC_CAP;
    const rows = this.db
      .prepare('SELECT id, content FROM memories WHERE embedding IS NULL AND archived_at IS NULL ORDER BY id DESC LIMIT ?')
      .all(cap) as unknown as Array<{ id: number; content: string }>;
    let embedded = 0;
    for (const r of rows) {
      try {
        const vec = await provider.embed(r.content);
        this.embedUpdateStmt.run(embeddingToBlob(vec), r.id);
        embedded++;
      } catch (err) {
        log.warn('backfill embed failed (skipped)', { memoryId: r.id, error: String(err) });
      }
    }
    if (rows.length > 0) log.info('memory embedding backfill pass complete', { embedded, scanned: rows.length });
    return embedded;
  }

  list(agentId: string, opts: ListOptions = {}): MemoryRow[] {
    const conds = ["(agent_id = ? OR category = 'shared')"];
    const params: Array<string | number> = [agentId];
    if (opts.category !== undefined) {
      conds.push('category = ?');
      params.push(opts.category);
    }
    if (!opts.includeArchived) conds.push('archived_at IS NULL');
    params.push(opts.limit ?? DEFAULT_LIST_LIMIT);
    const rows = this.db
      .prepare(`SELECT ${ROW_COLUMNS} FROM memories WHERE ${conds.join(' AND ')} ORDER BY id DESC LIMIT ?`)
      .all(...params) as unknown as DbMemoryRow[];
    return rows.map(mapRow);
  }

  /**
   * Patch content/keywords/category. The FTS index follows automatically via
   * the migration-defined triggers; a content change is re-embedded
   * (fire-and-forget, same guarantees as save).
   */
  update(id: number, patch: UpdateMemoryPatch, opts: { ownerAgentId?: string } = {}): boolean {
    const sets: string[] = [];
    const params: Array<string | number> = [];
    if (patch.content !== undefined) {
      sets.push('content = ?');
      params.push(patch.content);
    }
    if (patch.keywords !== undefined) {
      sets.push('keywords = ?');
      params.push(patch.keywords);
    }
    if (patch.category !== undefined) {
      sets.push('category = ?');
      params.push(patch.category);
    }
    if (sets.length === 0) return false;
    params.push(id);
    // owner scoping (SPEC §20.1): agent callers may only touch their own rows
    let where = 'id = ?';
    if (opts.ownerAgentId !== undefined) {
      where += ' AND agent_id = ?';
      params.push(opts.ownerAgentId);
    }
    const result = this.db.prepare(`UPDATE memories SET ${sets.join(', ')} WHERE ${where}`).run(...params);
    const changed = Number(result.changes) > 0;
    if (changed && patch.content !== undefined) this.scheduleEmbedding(id, patch.content);
    return changed;
  }

  /** Soft archive: stamps archived_at. The row remains forever (no DELETE). */
  archive(id: number, opts: { ownerAgentId?: string } = {}): boolean {
    if (opts.ownerAgentId !== undefined) {
      const result = this.db
        .prepare('UPDATE memories SET archived_at = ? WHERE id = ? AND archived_at IS NULL AND agent_id = ?')
        .run(isoNow(this.clock), id, opts.ownerAgentId);
      return Number(result.changes) > 0;
    }
    const result = this.archiveStmt.run(isoNow(this.clock), id);
    return Number(result.changes) > 0;
  }

  /**
   * Gentle forgetting: multiply salience of non-archived rows by `factor`,
   * never below `floor`, never removing anything. Returns rows touched.
   */
  decay(factor = DEFAULT_DECAY_FACTOR, floor = DEFAULT_DECAY_FLOOR): number {
    const result = this.decayStmt.run(floor, factor, floor);
    return Number(result.changes);
  }

  /**
   * Tier aging: hot rows untouched (by access or creation) for more than
   * `hotToColdAfterDays` days move to cold. Returns rows moved.
   */
  age(hotToColdAfterDays: number): number {
    const cutoff = new Date(this.clock.now().getTime() - hotToColdAfterDays * DAY_MS).toISOString();
    const result = this.ageStmt.run(cutoff);
    return Number(result.changes);
  }

  /** Live (non-archived) counts per category/sector + average salience; archived counted separately. */
  stats(agentId?: string): MemoryStats {
    const scope = agentId === undefined ? '' : ' AND agent_id = ?';
    const params: string[] = agentId === undefined ? [] : [agentId];
    const grouped = this.db
      .prepare(
        `SELECT category, sector, COUNT(*) AS n FROM memories
         WHERE archived_at IS NULL${scope} GROUP BY category, sector`,
      )
      .all(...params) as unknown as Array<{ category: MemoryCategory; sector: MemorySector; n: number }>;
    const totals = this.db
      .prepare(
        `SELECT COUNT(*) AS n, COALESCE(AVG(salience), 0) AS avg FROM memories
         WHERE archived_at IS NULL${scope}`,
      )
      .get(...params) as unknown as { n: number; avg: number };
    const archived = this.db
      .prepare(`SELECT COUNT(*) AS n FROM memories WHERE archived_at IS NOT NULL${scope}`)
      .get(...params) as unknown as { n: number };

    const byCategory: Record<MemoryCategory, number> = { hot: 0, warm: 0, cold: 0, shared: 0 };
    const bySector: Record<MemorySector, number> = { semantic: 0, episodic: 0 };
    for (const g of grouped) {
      byCategory[g.category] += g.n;
      bySector[g.sector] += g.n;
    }
    return { total: totals.n, byCategory, bySector, avgSalience: totals.avg, archived: archived.n };
  }

  /** Whether semantic (vector) search is actually available (a provider is wired). */
  embeddingEnabled(): boolean {
    return this.embedding !== undefined;
  }

  /** Count of non-archived memories that already carry an embedding (vector coverage). */
  embeddedCount(agentId?: string): number {
    const scope = agentId === undefined ? '' : ' AND agent_id = ?';
    const params: string[] = agentId === undefined ? [] : [agentId];
    const row = this.db
      .prepare(`SELECT COUNT(*) AS n FROM memories WHERE embedding IS NOT NULL AND archived_at IS NULL${scope}`)
      .get(...params) as unknown as { n: number };
    return row.n;
  }

  // --- internals ---

  /** Keyword candidates (FTS, LIKE fallback) WITHOUT the salience boost — the
   *  shared selection step for both `search` and `searchHybrid`. */
  private ftsCandidates(agentId: string, query: string, limit: number): MemoryRow[] {
    const ftsQuery = sanitizeFtsQuery(query);
    if (ftsQuery === '') return this.searchLike(agentId, query, limit);
    try {
      return this.searchFts(ftsQuery, agentId, limit);
    } catch (err) {
      log.warn('FTS query failed, falling back to LIKE', { query: ftsQuery, error: String(err) });
      return this.searchLike(agentId, query, limit);
    }
  }

  /** Recall side effect (SPEC §8/§9): boost salience (+0.1, capped) + stamp
   *  accessed_at on returned rows; mutates the rows to reflect the new state. */
  private applyBoost(rows: MemoryRow[]): void {
    const now = isoNow(this.clock);
    for (const row of rows) {
      this.boostStmt.run(SALIENCE_CAP, SALIENCE_BOOST, now, row.id);
      row.salience = Math.min(SALIENCE_CAP, row.salience + SALIENCE_BOOST);
      row.accessedAt = now;
    }
  }

  /** Recently-saved embedded rows in recall scope, with their decoded vectors.
   *  Malformed/dimension-mismatched blobs are skipped (graceful, never throws). */
  private embeddedRowsInScope(agentId: string, cap: number): Array<{ row: MemoryRow; vec: Float32Array }> {
    const rows = this.db
      .prepare(
        `SELECT ${ROW_COLUMNS}, embedding FROM memories
         WHERE (agent_id = ? OR category = 'shared') AND archived_at IS NULL AND embedding IS NOT NULL
         ORDER BY id DESC LIMIT ?`,
      )
      .all(agentId, cap) as unknown as Array<DbMemoryRow & { embedding: Uint8Array }>;
    const out: Array<{ row: MemoryRow; vec: Float32Array }> = [];
    for (const r of rows) {
      try {
        out.push({ row: mapRow(r), vec: blobToEmbedding(r.embedding) });
      } catch {
        /* malformed/dim-mismatch blob: skip (keeps hybrid graceful) */
      }
    }
    return out;
  }

  private searchFts(ftsQuery: string, agentId: string, limit: number): MemoryRow[] {
    const rows = this.ftsStmt.all(ftsQuery, agentId, limit) as unknown as DbMemoryRow[];
    return rows.map(mapRow);
  }

  private searchLike(agentId: string, rawQuery: string, limit: number): MemoryRow[] {
    const tokens = tokenizeQuery(rawQuery);
    if (tokens.length === 0) return [];
    // Tokens are letters/digits only, so no LIKE wildcard can be smuggled in.
    const clauses = tokens.map(() => '(content LIKE ? OR keywords LIKE ?)').join(' OR ');
    const params: Array<string | number> = [agentId];
    for (const t of tokens) {
      const pattern = `%${t}%`;
      params.push(pattern, pattern);
    }
    params.push(limit);
    const rows = this.db
      .prepare(
        `SELECT ${ROW_COLUMNS} FROM memories
         WHERE (agent_id = ? OR category = 'shared') AND archived_at IS NULL AND (${clauses})
         ORDER BY salience DESC, id DESC LIMIT ?`,
      )
      .all(...params) as unknown as DbMemoryRow[];
    return rows.map(mapRow);
  }

  /**
   * Fire-and-forget vectorization (SPEC §8). The async IIFE converts even a
   * synchronous provider throw into a caught rejection — a save can never be
   * blocked or failed by the embedding backend.
   */
  private scheduleEmbedding(id: number, content: string): void {
    const provider = this.embedding;
    if (!provider) return;
    void (async () => {
      const vec = await provider.embed(content);
      this.embedUpdateStmt.run(embeddingToBlob(vec), id);
    })().catch((err: unknown) => {
      log.warn('embedding failed (save unaffected)', { memoryId: id, error: String(err) });
    });
  }
}

function columnsOf(alias: string): string {
  return ROW_COLUMNS.split(', ')
    .map((c) => `${alias}.${c}`)
    .join(', ');
}
