// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (C) 2026 romcsibacsi
// This file is part of citadel (public open-core). See LICENSE.
// A commercial license without AGPL obligations is available — see COMMERCIAL-LICENSE.md (dual-license).
import type { Router } from '../router.js';
import { HttpError, sendJson } from '../router.js';
import type { AppContext } from '../../app/context.js';
import { sanitizeId } from '../../trust/sanitize.js';
import { appendDailyLog } from '../../memory/digest.js';
import { screenMemoryContent } from '../../memory/safety.js';
import type { MemoryCategory, MemorySector } from '../../memory/store.js';

const CATEGORIES = new Set(['hot', 'warm', 'cold', 'shared']);
const SECTORS = new Set(['semantic', 'episodic']);

/** Agents may only act in their own name; the operator names any agent. */
function resolveAgentId(c: { auth: { kind: string; agentId?: string } }, requested: string | null): string {
  if (c.auth.kind === 'agent') return sanitizeId(c.auth.agentId ?? '');
  const id = sanitizeId(requested ?? '');
  if (id === '') throw new HttpError(400, 'agent required');
  return id;
}

export function registerMemoryRoutes(router: Router, ctx: AppContext): void {
  router.get('/api/memories', (c) => {
    const agent = resolveAgentId(c, c.url.searchParams.get('agent'));
    const category = c.url.searchParams.get('category');
    const limitRaw = Number(c.url.searchParams.get('limit') ?? 100);
    sendJson(
      c.res,
      200,
      ctx.memory.list(agent, {
        ...(category !== null && CATEGORIES.has(category) ? { category: category as MemoryCategory } : {}),
        limit: Number.isFinite(limitRaw) ? limitRaw : 100,
        includeArchived: c.url.searchParams.get('includeArchived') === 'true',
      }),
    );
  });

  router.get('/api/memories/search', async (c) => {
    const agent = resolveAgentId(c, c.url.searchParams.get('agent'));
    const q = c.url.searchParams.get('q') ?? '';
    if (q.trim() === '') throw new HttpError(400, 'q required');
    // 'mode' is honored only when an embedding provider is wired; otherwise both
    // hybrid and fts resolve to keyword search (the UI hides Hybrid accordingly).
    const mode = c.url.searchParams.get('mode') === 'fts' ? 'fts' : 'hybrid';
    // Hybrid embeds the query (async) and fuses vector + keyword; fts (or no
    // provider) takes the sync keyword path. searchHybrid self-falls-back to FTS.
    const rows =
      mode === 'hybrid' && ctx.memory.embeddingEnabled()
        ? await ctx.memory.searchHybrid(agent, q, { mode })
        : ctx.memory.search(agent, q, { mode });
    sendJson(c.res, 200, rows);
  });

  /** Stats + vector-coverage; embeddingEnabled tells the UI whether Hybrid is real. */
  const statsWithVectors = (agentId?: string): Record<string, unknown> => ({
    ...ctx.memory.stats(agentId),
    embeddingEnabled: ctx.memory.embeddingEnabled(),
    embedded: ctx.memory.embeddedCount(agentId),
  });
  router.get('/api/memories/stats', (c) => {
    // agent callers are pinned to their own stats; only the operator sees the fleet
    if (c.auth.kind === 'agent') {
      sendJson(c.res, 200, statsWithVectors(sanitizeId(c.auth.agentId)));
      return;
    }
    const agent = c.url.searchParams.get('agent');
    sendJson(c.res, 200, statsWithVectors(agent !== null ? sanitizeId(agent) : undefined));
  });

  router.post('/api/memories', (c) => {
    const body = (c.body ?? {}) as {
      agentId?: string;
      category?: string;
      sector?: string;
      content?: string;
      keywords?: string;
      autoGenerated?: boolean;
    };
    const agentId = resolveAgentId(c, body.agentId ?? null);
    if (typeof body.content !== 'string' || body.content.trim() === '') throw new HttpError(400, 'content required');
    // safety filter (§6.3/§8): reject injection / shell-exec content on EVERY write
    if (!screenMemoryContent(body.content).ok) throw new HttpError(400, ctx.i18n.t('memory.error.rejected'));
    const category = CATEGORIES.has(body.category ?? '') ? (body.category as MemoryCategory) : 'warm';
    const sector = SECTORS.has(body.sector ?? '') ? (body.sector as MemorySector) : 'semantic';
    const id = ctx.memory.save({
      agentId,
      category,
      sector,
      content: body.content,
      ...(typeof body.keywords === 'string' ? { keywords: body.keywords } : {}),
      ...(body.autoGenerated === true ? { autoGenerated: true } : {}),
    });
    sendJson(c.res, 201, { id });
  });

  // mutations are owner-scoped for agent tokens (SPEC §20.1): an agent can
  // never read/tamper/suppress another agent's rows through these handlers
  router.patch('/api/memories/:id', (c) => {
    const body = (c.body ?? {}) as { content?: string; keywords?: string; category?: string };
    // safety filter (§6.3/§8): an edit that introduces injection/exec content is rejected too
    if (typeof body.content === 'string' && !screenMemoryContent(body.content).ok) throw new HttpError(400, ctx.i18n.t('memory.error.rejected'));
    const scope = c.auth.kind === 'agent' ? { ownerAgentId: sanitizeId(c.auth.agentId) } : {};
    const ok = ctx.memory.update(
      Number(c.params.id),
      {
        ...(typeof body.content === 'string' ? { content: body.content } : {}),
        ...(typeof body.keywords === 'string' ? { keywords: body.keywords } : {}),
        ...(body.category !== undefined && CATEGORIES.has(body.category)
          ? { category: body.category as MemoryCategory }
          : {}),
      },
      scope,
    );
    if (!ok) throw new HttpError(404, 'no such memory');
    sendJson(c.res, 200, { updated: Number(c.params.id) });
  });

  // "delete" is ARCHIVE — memories are never hard-deleted (SPEC §8, §20.4/8)
  router.delete('/api/memories/:id', (c) => {
    const scope = c.auth.kind === 'agent' ? { ownerAgentId: sanitizeId(c.auth.agentId) } : {};
    const ok = ctx.memory.archive(Number(c.params.id), scope);
    if (!ok) throw new HttpError(404, 'no such memory');
    sendJson(c.res, 200, { archived: Number(c.params.id) });
  });

  router.post('/api/memories/daily-log', (c) => {
    const body = (c.body ?? {}) as { agentId?: string; line?: string; day?: string };
    const agentId = resolveAgentId(c, body.agentId ?? null);
    if (typeof body.line !== 'string' || body.line.trim() === '') throw new HttpError(400, ctx.i18n.t('journal.contentRequired'));
    // stamp the day in the CONFIGURED timezone, not UTC, so an entry written near
    // midnight lands under the same local day the Daily-Log/recall reads use (§10) —
    // a raw-UTC stamp drifts a day off in the UTC-evening / local-night window.
    const day = body.day ?? new Intl.DateTimeFormat('en-CA', { timeZone: ctx.config.timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
    appendDailyLog(ctx.db, agentId, day, body.line);
    sendJson(c.res, 201, { logged: day });
  });

  /** Session-start replay (SPEC §8): recent transcript + the open question. */
  router.get('/api/memories/recall', (c) => {
    const agent = resolveAgentId(c, c.url.searchParams.get('agent'));
    const chat = c.url.searchParams.get('chat') ?? 'dashboard';
    sendJson(c.res, 200, {
      replay: ctx.ledger.buildReplay(agent, chat),
      openQuestion: ctx.ledger.openQuestion(agent, chat) ?? null,
    });
  });
}
